using System;
using System.Collections.Generic;
using RomesteadSaveInspector.Database;

namespace RomesteadSaveInspector.WinUI;

public static class GameTextDb
{
    private static readonly Dictionary<string, TextEntry> Texts = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Citizen_Efficiency*stats:name"] = new("Efficiency", "效率", "效率"),
        ["Citizen_ExperienceGain*stats:name"] = new("Experience gain", "经验值收益", "經驗值收益"),
        ["Citizen_Expertise*stats:name"] = new("Expertise", "专业知识", "專業知識"),
        ["Citizen_FoodCost*stats:name"] = new("Food cost", "食物消耗", "食物消耗"),
        ["Citizen_Happiness*stats:name"] = new("Happiness", "幸福度", "幸福度"),
        ["Citizen_LoyaltyGain*stats:name"] = new("Loyalty gain", "忠诚度收益", "忠誠度收益"),
        ["citizen_aura:buff:cornucopia*citizenaura:name"] = new("Cornucopia", "丰饶号角", "豐饒號角"),
        ["citizen_aura:buff:efficiency*citizenaura:name"] = new("Quick", "雷厉风行", "雷厲風行"),
        ["citizen_aura:buff:experience*citizenaura:name"] = new("Focused", "心无旁骛", "心無旁騖"),
        ["citizen_aura:buff:expertise*citizenaura:name"] = new("Meticulous", "一丝不苟", "一絲不苟"),
        ["citizen_aura:buff:happiness*citizenaura:name"] = new("Excited", "活力四射", "活力四射"),
        ["citizen_aura:buff:loyalty*citizenaura:name"] = new("Impressionable", "人云亦云", "人云亦云"),
        ["citizen_aura:buff:town_defence*citizenaura:name"] = new("Well Defended", "固若金汤", "Well Defended"),
        ["citizen_aura:buff:venus_citizen_expertise*citizenaura:name"] = new("Prosperous Ideals", "繁荣理想", "繁榮理想"),
        ["citizen_aura:buff:venus_embrace*citizenaura:name"] = new("Venus' Embrace", "维纳斯的拥抱", "維納斯的擁抱"),
        ["citizen_aura:debuff:anxiety*citizenaura:name"] = new("Anxiety", "忧心忡忡", "憂心忡忡"),
        ["citizen_aura:debuff:efficiency*citizenaura:name"] = new("Tentative", "犹豫不决", "猶豫不決"),
        ["citizen_aura:debuff:experience*citizenaura:name"] = new("Unfocused", "心不在焉", "心不在焉"),
        ["citizen_aura:debuff:expertise*citizenaura:name"] = new("Sloppy", "马马虎虎", "馬馬虎虎"),
        ["citizen_aura:debuff:food*citizenaura:name"] = new("Gluttonous", "暴饮暴食", "暴飲暴食"),
        ["citizen_aura:debuff:happiness*citizenaura:name"] = new("Depressed", "郁郁寡欢", "鬱鬱寡歡"),
        ["citizen_aura:debuff:loyalty*citizenaura:name"] = new("Disloyal", "见异思迁", "見異思遷"),
        ["citizen_aura:gift:0*citizenaura:name"] = new("Nice Gift", "良赠好礼", "良贈好禮"),
        ["citizen_aura:gift:1*citizenaura:name"] = new("Great Gift", "怡人佳礼", "怡人佳禮"),
        ["citizen_aura:gift:2*citizenaura:name"] = new("Beautiful Gift", "精美臻礼", "精美臻禮"),
        ["citizen_aura:gift:bad*citizenaura:name"] = new("Hostile Gift", "恶毒歹礼", "惡毒歹禮"),
        ["citizen_aura:gift:food_cost_reduction*citizenaura:name"] = new("Satiated", "吃饱喝足", "吃飽喝足"),
        ["citizen_aura:injury:broken_arm*citizenaura:name"] = new("Broken Arm", "手臂骨折", "手臂骨折"),
        ["citizen_aura:injury:broken_leg*citizenaura:name"] = new("Broken Leg", "腿部骨折", "腿部骨折"),
        ["citizen_aura:injury:broken_rib*citizenaura:name"] = new("Broken Rib", "肋骨骨折", "肋骨骨折"),
        ["citizen_aura:injury:concussion*citizenaura:name"] = new("Concussion", "脑震荡", "腦震盪"),
        ["citizen_aura:injury:infected_wound*citizenaura:name"] = new("Infected Wound", "伤口感染", "傷口感染"),
        ["citizen_aura:injury:tetanus*citizenaura:name"] = new("Tetanus", "破伤风", "破傷風"),
        ["citizen_aura:injury:tinnitus*citizenaura:name"] = new("Tinnitus", "耳鸣", "耳鳴"),
        ["citizen_aura:injury:wounded_eye*citizenaura:name"] = new("Wounded Eye", "眼部受伤", "眼部受傷"),
        ["citizen_aura:loyalty:1*citizenaura:name"] = new("Loyalty - Level 1", "忠诚度 - 1级", "忠誠度 - 1級"),
        ["citizen_aura:loyalty:2*citizenaura:name"] = new("Loyalty - Level 2", "忠诚度 - 2级", "忠誠度 - 2級"),
        ["citizen_aura:loyalty:3*citizenaura:name"] = new("Loyalty - Level 3", "忠诚度 - 3级", "忠誠度 - 3級"),
        ["citizen_aura:loyalty:4*citizenaura:name"] = new("Loyalty - Level 4", "忠诚度 - 4级", "忠誠度 - 4級"),
        ["citizen_aura:wine:0*citizenaura:name"] = new("High Spirits", "情绪高涨", "情緒高漲"),
        ["female_name_0"] = new("Aelia", "艾莉娅", "艾莉婭"),
        ["female_name_1"] = new("Aemilia", "艾米莉娅", "艾米莉婭"),
        ["female_name_10"] = new("Caelina", "凯利娜", "凱利娜"),
        ["female_name_11"] = new("Caesonia", "凯索尼娅", "凱索尼婭"),
        ["female_name_12"] = new("Calpurnia", "卡尔普尔尼娅", "卡爾普爾尼婭"),
        ["female_name_13"] = new("Camilla", "卡米拉", "卡蜜拉"),
        ["female_name_14"] = new("Cassia", "卡西娅", "凱西婭"),
        ["female_name_15"] = new("Claudia", "克劳迪娅", "克勞迪婭"),
        ["female_name_16"] = new("Cloelia", "克勒利娅", "克勒利婭"),
        ["female_name_17"] = new("Cornelia", "科尔内利娅", "科爾內利婭"),
        ["female_name_18"] = new("Crispina", "克里斯皮娜", "克裡斯皮娜"),
        ["female_name_19"] = new("Decima", "德西玛", "德西瑪"),
        ["female_name_2"] = new("Agrippina", "阿格里皮娜", "阿格裡皮娜"),
        ["female_name_20"] = new("Domitilla", "多米蒂拉", "多米蒂拉"),
        ["female_name_21"] = new("Drusilla", "德鲁西拉", "德魯西拉"),
        ["female_name_22"] = new("Fabia", "法比娅", "法比婭"),
        ["female_name_23"] = new("Faustina", "福斯蒂娜", "福斯蒂娜"),
        ["female_name_24"] = new("Flaviana", "弗拉维娅娜", "弗拉維婭娜"),
        ["female_name_25"] = new("Floriana", "弗洛丽娅娜", "弗洛麗婭娜"),
        ["female_name_26"] = new("Gaia", "盖娅", "蓋婭"),
        ["female_name_27"] = new("Galla", "加拉", "加拉"),
        ["female_name_28"] = new("Helvia", "赫尔维娅", "赫爾維婭"),
        ["female_name_29"] = new("Herminia", "赫尔米尼娅", "赫爾米尼婭"),
        ["female_name_3"] = new("Alba", "阿尔巴", "阿爾巴"),
        ["female_name_30"] = new("Hilaria", "希拉莉娅", "希拉莉婭"),
        ["female_name_31"] = new("Horatia", "霍拉提娅", "霍拉提婭"),
        ["female_name_32"] = new("Hortensia", "霍尔滕西亚", "霍爾滕西亞"),
        ["female_name_33"] = new("Julia", "朱莉娅", "朱麗亞"),
        ["female_name_34"] = new("Laelia", "莱莉娅", "萊莉婭"),
        ["female_name_35"] = new("Laurentia", "劳伦提娅", "勞倫提婭"),
        ["female_name_36"] = new("Livia", "利维娅", "利維婭"),
        ["female_name_37"] = new("Liviana", "利维亚娜", "利維亞娜"),
        ["female_name_38"] = new("Longina", "隆吉娜", "隆吉娜"),
        ["female_name_39"] = new("Lucia", "卢西娅", "盧西婭"),
        ["female_name_4"] = new("Antonia", "安东尼娅", "安東尼婭"),
        ["female_name_40"] = new("Lucretia", "卢克雷提娅", "盧克雷提婭"),
        ["female_name_41"] = new("Marcella", "马尔切拉", "瑪律切拉"),
        ["female_name_42"] = new("Marcia", "马尔西亚", "瑪律西亞"),
        ["female_name_43"] = new("Marina", "玛丽娜", "瑪麗娜"),
        ["female_name_44"] = new("Maxima", "马克西玛", "馬克西瑪"),
        ["female_name_45"] = new("Octavia", "奥克塔维娅", "奧克塔維婭"),
        ["female_name_46"] = new("Paulina", "保利娜", "保利娜"),
        ["female_name_47"] = new("Petronia", "佩特罗尼娅", "佩特羅尼婭"),
        ["female_name_48"] = new("Pomponia", "庞庞尼娅", "龐龐尼婭"),
        ["female_name_49"] = new("Porcia", "波尔恰", "波爾恰"),
        ["female_name_5"] = new("Aquilina", "阿奎莉娜", "阿奎莉娜"),
        ["female_name_50"] = new("Priscilla", "普里西拉", "普裡西拉"),
        ["female_name_51"] = new("Quintina", "昆蒂娜", "昆蒂娜"),
        ["female_name_52"] = new("Rufina", "鲁菲娜", "魯菲娜"),
        ["female_name_53"] = new("Sabina", "萨比娜", "薩比娜"),
        ["female_name_54"] = new("Saturnia", "萨图尔尼娅", "薩圖爾尼婭"),
        ["female_name_55"] = new("Septima", "塞普蒂玛", "塞普蒂瑪"),
        ["female_name_56"] = new("Severina", "塞维丽娜", "塞維麗娜"),
        ["female_name_57"] = new("Silvia", "西尔维娅", "西爾維婭"),
        ["female_name_58"] = new("Tacita", "塔西塔", "塔西塔"),
        ["female_name_59"] = new("Tatiana", "塔蒂安娜", "塔蒂安娜"),
        ["female_name_6"] = new("Augusta", "奥古斯塔", "奧古斯塔"),
        ["female_name_60"] = new("Tertia", "特尔提娅", "特爾提婭"),
        ["female_name_61"] = new("Titania", "提塔尼娅", "提塔尼婭"),
        ["female_name_62"] = new("Valentina", "瓦伦蒂娜", "瓦倫蒂娜"),
        ["female_name_63"] = new("Valeria", "瓦莱丽娅", "瓦萊麗婭"),
        ["female_name_64"] = new("Varinia", "瓦里尼娅", "瓦裡尼婭"),
        ["female_name_65"] = new("Vibiana", "维比安娜", "維比安娜"),
        ["female_name_66"] = new("Vita", "维塔", "維塔"),
        ["female_name_7"] = new("Aurelia", "奥雷莉娅", "奧雷莉婭"),
        ["female_name_8"] = new("Aureliana", "奥雷利亚娜", "奧雷利亞娜"),
        ["female_name_9"] = new("Blandina", "布兰迪娜", "布蘭迪娜"),
        ["job:baker*job:name"] = new("Baker", "烘焙师", "烘焙師"),
        ["job:baker*job:name:feminine"] = new("Baker", "烘焙师", "烘焙師"),
        ["job:blacksmith*job:name"] = new("Blacksmith", "锻工铺", "鍛工鋪"),
        ["job:blacksmith*job:name:feminine"] = new("Blacksmith", "锻工铺", "鍛工鋪"),
        ["job:carpenter*job:name"] = new("Carpenter", "木匠", "木匠"),
        ["job:carpenter*job:name:feminine"] = new("Carpenter", "木匠", "木匠"),
        ["job:carrier*job:name"] = new("Carrier", "搬运工 ", "搬運工 "),
        ["job:carrier*job:name:feminine"] = new("Carrier", "搬运工 ", "搬運工 "),
        ["job:digger*job:name"] = new("Digger", "挖土工", "挖土工"),
        ["job:digger*job:name:feminine"] = new("Digger", "挖土工", "挖土工"),
        ["job:farmer*job:name"] = new("Farmer", "农民", "農民"),
        ["job:farmer*job:name:feminine"] = new("Farmer", "农民", "農民"),
        ["job:leatherworker*job:name"] = new("Leatherworker", "制革工坊", "製革工坊"),
        ["job:leatherworker*job:name:feminine"] = new("Leatherworker", "制革工坊", "製革工坊"),
        ["job:lumberjack*job:name"] = new("Lumberjack", "伐木工", "伐木工"),
        ["job:lumberjack*job:name:feminine"] = new("Lumberjack", "伐木工", "伐木工"),
        ["job:merchant*job:name"] = new("Merchant", "商人", "商人"),
        ["job:merchant*job:name:feminine"] = new("Merchant", "商人", "商人"),
        ["job:miner*job:name"] = new("Miner", "矿工", "礦工"),
        ["job:miner*job:name:feminine"] = new("Miner", "矿工", "礦工"),
        ["job:philosopher*job:name"] = new("Philosopher", "哲学家", "哲學家"),
        ["job:philosopher*job:name:feminine"] = new("Philosopher", "哲学家", "哲學家"),
        ["job:potter*job:name"] = new("Potter", "陶工", "陶工"),
        ["job:potter*job:name:feminine"] = new("Potter", "陶工", "陶工"),
        ["job:priest*job:name"] = new("Priest", "牧师", "牧師"),
        ["job:priest*job:name:feminine"] = new("Priestess", "牧师", "牧師"),
        ["job:sculptor*job:name"] = new("Sculptor", "雕塑家", "雕塑師"),
        ["job:sculptor*job:name:feminine"] = new("Sculptor", "雕塑家", "雕塑師"),
        ["job:unemployed*job:name"] = new("Otiosus", "闲人", "閒人"),
        ["job:unemployed*job:name:feminine"] = new("Otiosus", "闲人", "閒人"),
        ["male_name_0"] = new("Aelius", "艾利乌斯", "艾利烏斯"),
        ["male_name_1"] = new("Aemilianus", "埃米利阿努斯", "埃米利阿努斯"),
        ["male_name_10"] = new("Brutus", "布鲁图斯", "布魯圖斯"),
        ["male_name_11"] = new("Caelius", "凯利乌斯", "凱利烏斯"),
        ["male_name_12"] = new("Caesonius", "凯索尼乌斯", "凱索尼烏斯"),
        ["male_name_13"] = new("Calpurnius", "卡尔普尔尼乌斯", "卡爾普爾尼烏斯"),
        ["male_name_14"] = new("Camillus", "卡米卢斯", "卡米盧斯"),
        ["male_name_15"] = new("Cassius", "卡西乌斯", "凱西烏斯"),
        ["male_name_16"] = new("Claudius", "克劳狄乌斯", "克勞狄烏斯"),
        ["male_name_17"] = new("Cloelius", "克勒利乌斯", "克勒利烏斯"),
        ["male_name_18"] = new("Cornelius", "科尔内利乌斯", "科爾內利烏斯"),
        ["male_name_19"] = new("Crispus", "克里斯普斯", "克裡斯普斯"),
        ["male_name_2"] = new("Agrippa", "阿格里帕", "阿格裡帕"),
        ["male_name_20"] = new("Decimus", "德基穆斯", "德基穆斯"),
        ["male_name_21"] = new("Domitius", "多米提乌斯", "多米提烏斯"),
        ["male_name_22"] = new("Drusus", "德鲁苏斯", "德魯蘇斯"),
        ["male_name_23"] = new("Fabian", "法比安", "法比安"),
        ["male_name_24"] = new("Faustus", "福斯图斯", "福斯圖斯"),
        ["male_name_25"] = new("Flavius", "弗拉维乌斯", "弗拉維烏斯"),
        ["male_name_26"] = new("Florus", "弗洛鲁斯", "弗洛魯斯"),
        ["male_name_27"] = new("Gaius", "盖乌斯", "蓋烏斯"),
        ["male_name_28"] = new("Gallus", "加卢斯", "加盧斯"),
        ["male_name_29"] = new("Helvius", "赫尔维乌斯", "赫爾維烏斯"),
        ["male_name_3"] = new("Albus", "阿尔布斯", "阿爾布斯"),
        ["male_name_30"] = new("Herminius", "赫尔米尼乌斯", "赫爾米尼烏斯"),
        ["male_name_31"] = new("Hilarius", "希拉留斯", "希拉留斯"),
        ["male_name_32"] = new("Horatius", "霍拉提乌斯", "霍拉提烏斯"),
        ["male_name_33"] = new("Hortensius", "霍尔滕修斯", "霍爾滕修斯"),
        ["male_name_34"] = new("Ignatius", "伊格纳修斯", "伊格納修斯"),
        ["male_name_35"] = new("Julius", "尤利乌斯", "尤利烏斯"),
        ["male_name_36"] = new("Laelius", "莱利乌斯", "萊利烏斯"),
        ["male_name_37"] = new("Laurentinus", "劳伦提努斯", "勞倫提努斯"),
        ["male_name_38"] = new("Livianus", "利维阿努斯", "利維阿努斯"),
        ["male_name_39"] = new("Livius", "利维乌斯", "利維烏斯"),
        ["male_name_4"] = new("Antonius", "安东尼乌斯", "安東尼烏斯"),
        ["male_name_40"] = new("Longinus", "隆吉努斯", "隆吉努斯"),
        ["male_name_41"] = new("Lucius", "卢修斯", "盧修斯"),
        ["male_name_42"] = new("Lucretius", "卢克雷修斯", "盧克雷修斯"),
        ["male_name_43"] = new("Marcellinus", "马塞利努斯", "馬塞利努斯"),
        ["male_name_44"] = new("Marcus", "马库斯", "馬庫斯"),
        ["male_name_45"] = new("Marinus", "马里努斯", "馬里努斯"),
        ["male_name_46"] = new("Maximus", "马克西穆斯", "馬克西穆斯"),
        ["male_name_47"] = new("Octavius", "奥克塔维乌斯", "奧克塔維烏斯"),
        ["male_name_48"] = new("Paulus", "保卢斯", "保盧斯"),
        ["male_name_49"] = new("Petronius", "佩特罗尼乌斯", "佩特羅尼烏斯"),
        ["male_name_5"] = new("Aquila", "阿奎拉", "阿奎拉"),
        ["male_name_50"] = new("Pomponius", "庞庞尼乌斯", "龐龐尼烏斯"),
        ["male_name_51"] = new("Porcius", "波尔丘斯", "波爾丘斯"),
        ["male_name_52"] = new("Priscus", "普里斯库斯", "普裡斯庫斯"),
        ["male_name_53"] = new("Quintus", "昆图斯", "昆圖斯"),
        ["male_name_54"] = new("Rufus", "鲁弗斯", "魯弗斯"),
        ["male_name_55"] = new("Sabinus", "萨比努斯", "薩比努斯"),
        ["male_name_56"] = new("Saturnius", "萨图尔尼乌斯", "薩圖爾尼烏斯"),
        ["male_name_57"] = new("Septimus", "塞普蒂穆斯", "塞普蒂穆斯"),
        ["male_name_58"] = new("Severus", "塞维鲁斯", "塞維魯斯"),
        ["male_name_59"] = new("Silvanus", "西凡纳斯", "西凡納斯"),
        ["male_name_6"] = new("Augustus", "奥古斯都", "奧古斯都"),
        ["male_name_60"] = new("Tacitus", "塔西图斯", "塔西圖斯"),
        ["male_name_61"] = new("Tatianus", "塔提亚努斯", "塔提亞努斯"),
        ["male_name_62"] = new("Tertius", "特尔提乌斯", "特爾提烏斯"),
        ["male_name_63"] = new("Titus", "提图斯", "提圖斯"),
        ["male_name_64"] = new("Valentinus", "瓦伦提努斯", "瓦倫提努斯"),
        ["male_name_65"] = new("Valerius", "瓦莱里乌斯", "瓦萊裡烏斯"),
        ["male_name_66"] = new("Varius", "瓦里乌斯", "瓦裡烏斯"),
        ["male_name_67"] = new("Vibius", "维比乌斯", "維比烏斯"),
        ["male_name_68"] = new("Vitus", "维图斯", "維圖斯"),
        ["male_name_7"] = new("Aurelius", "奥雷利乌斯", "奧雷利烏斯"),
        ["male_name_8"] = new("Aurelianus", "奥雷利亚努斯", "奧雷利亞努斯"),
        ["male_name_9"] = new("Blandus", "布兰杜斯", "布蘭杜斯"),
    };

    public static string Get(string key, string language)
    {
        if (string.IsNullOrWhiteSpace(key)) return string.Empty;

        // Runtime database first. This allows game text / NPC names / job names / trait names
        // to be updated from data/game_text.json or from the detected game directory without
        // changing C# source code.
        var runtimeValue = RuntimeGameDatabase.GetText(key.Trim(), language);
        if (!string.IsNullOrWhiteSpace(runtimeValue)) return runtimeValue;

        if (!Texts.TryGetValue(key.Trim(), out var entry)) return string.Empty;
        var normalized = RomesteadItemRecord.NormalizeLanguage(language);
        return normalized switch
        {
            "zh-hans" => entry.ZhHans,
            "zh-hant" => entry.ZhHant,
            _ => entry.En
        };
    }

    public static string GetAny(string id, string language, params string[] suffixes)
    {
        if (string.IsNullOrWhiteSpace(id)) return string.Empty;
        var raw = id.Trim();
        var direct = Get(raw, language);
        if (!string.IsNullOrWhiteSpace(direct)) return direct;
        foreach (var suffix in suffixes)
        {
            var value = Get(raw + suffix, language);
            if (!string.IsNullOrWhiteSpace(value)) return value;
        }
        return string.Empty;
    }

    private sealed record TextEntry(string En, string ZhHans, string ZhHant);
}